export const INITIAL_SETUP_REQUIRED = "INITIAL_SETUP_REQUIRED";
export const PRIMARY_DEVICE_ID = "PRIMARY_DEVICE_ID";
export const PRIMARY_DEVICE_NAME = "PRIMARY_DEVICE_NAME";
export const CHANGE_THRESHOLD_KEY = "CHANGE_THRESHOLD_KEY";
export const THROTTLE_TIME_KEY = "THROTTLE_TIME_KEY";
export const REVERSE_CAMERA = "REVERSE_CAMERA";
export const PLAY_SOUND = "PLAY_SOUND";
export const OUTPUT_TYPE_NAME = "OUTPUT_TYPE_NAME";
