export const INITIAL_SETUP_REQUIRED = "INITIAL_SETUP_REQUIRED";
export const PRIMARY_DEVICE_ID = "PRIMARY_DEVICE_ID";
export const PRIMARY_DEVICE_NAME = "PRIMARY_DEVICE_NAME";
export const CHANGE_THRESHOLD_KEY = "CHANGE_THRESHOLD_KEY";
export const THROTTLE_TIME_KEY = "THROTTLE_TIME_KEY";
