name: Build and Release
# This will change later, its on pull request for debugging purposes.
# When its done we want to run on main branch commits
on: [pull_request]

jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v2
      - name: Set Up Python
        uses: actions/setup-python@v2
      - uses: actions/cache@v2
        name: Cache dependencies
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install dependencies
        run: pip install -r ./eye_commander/requirements.txt
      - name: Install PyInstaller
        run: pip install pyinstaller
      - name: Bundle with pyinstaller
        run: pyinstaller entry.py
      - name: Upload Build
        uses: actions/upload-artifact@v2
          with:
            name: build
            path: dist
            retention-days: 1
