name: Build and Release
# This will change later, its on pull request for debugging purposes.
# When its done we want to run on main branch commits
on: [pull_request]

jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v2
      - name: Set Up Python
        uses: actions/setup-python@v2
      - name: Install dependencies
        run: pip install -r ./eye_commander/requirements.txt
