name: Comment on PR
on:
  workflow_run:
    workflows: [pull_request]
    types: [completed]

jobs:
  comment-on-pr:
    name: Add a link to an artifact to a PR
    runs-on: ubuntu-latest
    steps:
      - name: Add a link to an artifact to a PR
        uses: tonyhallett/artifacts-url-comments@v1.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          prefix: Here are the artifacts
          suffix: Have a nice day.
          format: name
          addTo: pull
