name: Release template
on:
  release:
    types: # This configuration does not affect the page_build event above
      - created

jobs:
  ChangeReleaseBody:
    runs-on: ubuntu-latest
    steps:
      - name: get version
        id: get_version
        run: |
          echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
      - name: update release
        id: update_release
        uses: tubone24/update_release@v1.0
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          body: |
            To install on your machine download the installer below.

            On *WINDOWS* you should download `EyeCommander-x.x.x.Setup.exe` file.

            On *OSx* you should download `EyeCommander.dmg`
